version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash -e
    steps:
       - run:
           name: Install Homebrew
           command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
       - run:
           name: Upgrade git to latest version, if needed.
           command: brew upgrade git || echo "Latest version of git has already been installed. Okay."
       - run: 
           name: Clone main iRODS repository
           command: git clone https://github.com/irods/irods.git
       - run:
           name: Clone iRODS dependencies repository
           command: git clone https://github.com/irods/externals.git
       - run: 
           name: Install prerequisites for dependencies
           working_directory: ~/project/externals
           command: ./install_prerequisites.py
       - run:
           name: Adjust externals makefile to send all output to stdout
           working_directory: ~/project/externals
           command: sed -i .bak 's/ > .*\.log 2>\&1$//' Makefile
       - run:
           name: Build externals
           working_directory: ~/project/externals
           command: make
