version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash -e
    steps:
      - run:
        name: Install Homebrew
        command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run: 
        name: Clone main iRODS repository
        command: git clone https://github.com/irods/irods.git
      - run:
        name: Clone iRODS dependencies repository
        command: https://github.com/irods/externals.git
      - run: 
        name: Install prerequisites for dependencies
        working_directory: ~/project/externals
        command: ./install_prerequisites.py
      - run: 
        name: Build dependencies
        working_directory: ~/project/externals
        command: make
